name: Package Addon
on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Retail Package
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
      env:
         GITHUB_OAUTH: ${{ secrets.OAUTH_TOKEN }}
